# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c7ppib77y-capi-aws
  namespace: c7ppib77y
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c7ppib77y-capi-aws
subjects:
- kind: ServiceAccount
  name: c7ppib77y-capi-aws
